services:
  hostly:
    image: "ghcr.io/khulnasoft/hostly:${LATEST_IMAGE:-latest}"
    volumes:
      - type: bind
        source: /data/hostly/source/.env
        target: /var/www/html/.env
        read_only: true
      - /data/hostly/ssh:/var/www/html/storage/app/ssh
      - /data/hostly/applications:/var/www/html/storage/app/applications
      - /data/hostly/databases:/var/www/html/storage/app/databases
      - /data/hostly/services:/var/www/html/storage/app/services
      - /data/hostly/backups:/var/www/html/storage/app/backups
      - /data/hostly/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance
    environment:
      - APP_ENV=production
      - APP_NAME
      - APP_ID
      - APP_KEY
      - APP_URL
      - APP_DEBUG
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_CONNECTION
      - QUEUE_CONNECTION
      - REDIS_HOST
      - REDIS_PASSWORD
      - HORIZON_BALANCE
      - HORIZON_MIN_PROCESSES
      - HORIZON_MAX_PROCESSES
      - HORIZON_BALANCE_MAX_SHIFT
      - HORIZON_BALANCE_COOLDOWN
      - SSL_MODE=off
      - PHP_MEMORY_LIMIT
      - PHP_PM_CONTROL=dynamic
      - PHP_PM_START_SERVERS=1
      - PHP_PM_MIN_SPARE_SERVERS=1
      - PHP_PM_MAX_SPARE_SERVERS=10
      - PUSHER_HOST
      - PUSHER_BACKEND_HOST
      - PUSHER_PORT
      - PUSHER_BACKEND_PORT
      - PUSHER_SCHEME
      - PUSHER_APP_ID
      - PUSHER_APP_KEY
      - PUSHER_APP_SECRET
      - TERMINAL_PROTOCOL
      - TERMINAL_HOST
      - TERMINAL_PORT
      - AUTOUPDATE
      - SSH_MUX_ENABLED
      - SSH_MUX_PERSIST_TIME
    ports:
      - "${APP_PORT:-8000}:80"
    expose:
      - "${APP_PORT:-8000}"
    healthcheck:
      test: curl --fail http://127.0.0.1:80/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy
  postgres:
    volumes:
      - hostly-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE:-hostly}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}", "-d", "${DB_DATABASE:-hostly}" ]
      interval: 5s
      retries: 10
      timeout: 2s
  redis:
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - hostly-redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
  soketi:
    image: 'ghcr.io/khulnasoft/hostly-realtime:1.0.4'
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "6002:6002"
    volumes:
      - /data/hostly/ssh:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "${APP_NAME:-Hostly}"
      SOKETI_DEBUG: "${SOKETI_DEBUG:-false}"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 2s

volumes:
  hostly-db:
    name: hostly-db
  hostly-redis:
    name: hostly-redis

networks:
  hostly:
    external: true
