services:
    hostly:
        container_name: hostly
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - hostly
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: hostly-db
        restart: always
        networks:
            - hostly
    redis:
        image: redis:alpine
        container_name: hostly-redis
        restart: always
        networks:
            - hostly
    soketi:
        container_name: hostly-realtime
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        restart: always
        networks:
            - hostly
networks:
    hostly:
        name: hostly
        driver: bridge
        external: false
