services:
  app:
    image: 'nginx'
    tty: true
    ports:
      - '3333:80'
    labels: 
      - traefik.http.middlewares.custom-auth.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG
  app2:
    image: 'nginx'
    labels: 
      - traefik.http.middlewares.custom-auth2.basicauth.users=test:$2y$05$ok6tRzMf9LwTHibBjtwcJeDEPEr6f/gTNRlHRNthzVbF77PWPu2hK
  app3:
    image: 'nginx'
    labels:
      - traefik.http.middlewares.custom-auth3.basicauth.users=test:$2y$05$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m 
  db:
    image: 'postgres:alpine'
    volumes:
      - 'store:/store'

volumes:
  store:
    driver: local
